# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty
#relative_permalinks: true

# Setup
title:              RAPID(C) 
tagline:             'Write Your Own Approximate Apps'
description:         'An on-going work that enables programmers to write apps with approximation easily (hopefully).'
url:                 https://niuye8911.github.io/rapid-linux
baseurl:             ''
paginate:            5

# About/contact
author:
  name:              Liu Liu
  url:               https://twitter.com/mdo
  email:             niuye8911@gmail.com

# Custom vars
version:             1.0.0

plugins: [jekyll-paginate]
