name: Solar Theme
url: https://niuye8911.github.io/rapidlib-linux/
description: A stylish blog using the Solarized color palette

permalink: /:year/:month/:day/:title/
paginate: 10

gems: [jekyll-paginate]
gems: [jekyll]
exclude: ['README.md', 'Gemfile.lock', 'Gemfile', 'Rakefile']
